<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [37]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [38]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('listings_Florencia.csv')
data.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,31840,https://www.airbnb.com/rooms/31840,20260626225546,2026-06-27,city scrape,Residenza Martin Classic room,"Nice, private and quiet double room, classic s...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,380378,...,4.91,4.90,4.71,IT048017B4R5K5BW8E,NaN,22,13,9,0,1.05
1,32180,https://www.airbnb.com/rooms/32180,20260626225546,2026-06-27,city scrape,Charming Gem - Oltrarno City centre,.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,13925330,...,4.72,4.84,4.84,IT048017C232S8WUEN,NaN,1,1,0,0,0.24
2,39115,https://www.airbnb.com/rooms/39115,20260626225546,2026-06-27,city scrape,Central Double Shared Bathroom,"Double Room Shared Bathroom: comfortable, larg...",NaN,https://a0.muscache.com/pictures/17793998/5f09...,167739,...,4.75,4.92,4.57,IT048017B9LED47MUB,NaN,11,3,8,0,0.48
3,39165,https://www.airbnb.com/rooms/39165,20260626225546,2026-06-27,city scrape,Florence Central Double Private Bathroom,"Double room private bathroom: comfortable, lar...",NaN,https://a0.muscache.com/pictures/7e94f597-ac04...,167739,...,4.65,4.96,4.43,IT048017B9LED47MUB,NaN,11,3,8,0,0.13
4,39822,https://www.airbnb.com/rooms/39822,20260626225546,2026-06-27,city scrape,Apartment Santa Monaca Oltrarno old town,Location details.<br />The bridge right next t...,NaN,https://a0.muscache.com/pictures/51118538/b6b9...,154769,...,4.74,4.89,4.54,IT048017C2VVSRW6CW,NaN,3,3,0,0,0.20

In [39]:
columnas = [
    "id",
    "name",
    "host_id",
    "host_name",
    "hosts_time_as_user_years",
    "hosts_time_as_host_years",
    "host_location",
    "host_is_superhost",
    "host_listings_count",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "amenities",
    "price_quote_checkin_date",
    "price_quote_checkout_date",
    "price_quote_total_price",
    "price_quote_price_per_night",
    "minimum_nights",
    "maximum_nights",
    "has_availability",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "first_review",
    "last_review",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "license",
    "calculated_host_listings_count",
    "calculated_host_listings_count_entire_homes",
    "reviews_per_month"
]
data = data[columnas]
data

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13467,1715912359275006217,Central Station Elegant Boutique Room With Ens...,673533626,Lorenzo,1,1,NaN,t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13468,1715924716827942680,Central Station Grand Boutique Room With Ensuite,673533626,Lorenzo,1,1,NaN,t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13469,1715936169133608202,Central Station Modern Boutique Room With Ensuite,673533626,Lorenzo,1,1,NaN,t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13470,1715980987031944374,Ognissanti Blue House by Maison Florence,47559514,Maison Florence,10,2,"Florence, Italy",f,31,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2X4FYIGFF,31,31,NaN
13471,1715987897090686076,Stanza privata con bagno privato e AC in centro,66886740,Rosanna,10,7,"Florence, Italy",f,30,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,0,NaN

In [40]:
# Seleccionar únicamente las 50 columnas
data = data[columnas]

# Crear una copia con esas 50 columnas
data2 = data.copy()

# Identificar valores nulos solamente en las 50 columnas
valores_nulos = data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                  2795
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                      1778
bedrooms                                       1634
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                        1024
price_quote_price_per_night                    1024
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [41]:
data2 = data.copy()

In [42]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                  2795
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                      1778
bedrooms                                       1634
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                        1024
price_quote_price_per_night                    1024
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [43]:
#Identificar valores nulos por dataframe
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(26073)

**Métodos de Sustitución de Valores Nulos**

In [44]:
#Realizamos una copia del dataframe
data2=data.copy()

In [45]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 13472 entries, 0 to 13471
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           13472 non-null  int64
 1   name                                         13472 non-null  str
 2   host_id                                      13472 non-null  int64
 3   host_name                                    13472 non-null  str
 4   hosts_time_as_user_years                     13472 non-null  int64
 5   hosts_time_as_host_years                     13472 non-null  int64
 6   host_location                                10677 non-null  str
 7   host_is_superhost                            13472 non-null  str
 8   host_listings_count                          13472 non-null  int64
 9   host_has_profile_pic                         13472 non-null  str
 10  host_identity_verified                       13472 non-null  str
 11  neighbourhood_cleansed                       13472 non-null  str
 12  latitude                                     13472 non-null  float64
 13  longitude                                    13472 non-null  float64
 14  property_type                                13472 non-null  str
 15  room_type                                    13472 non-null  str
 16  accommodates                                 13472 non-null  int64
 17  bathrooms                                    11694 non-null  float64
 18  bedrooms                                     11838 non-null  float64
 19  beds                                         12104 non-null  float64
 20  amenities                                    13472 non-null  str
 21  price_quote_checkin_date                     12684 non-null  str
 22  price_quote_checkout_date                    12684 non-null  str
 23  price_quote_total_price                      12448 non-null  float64
 24  price_quote_price_per_night                  12448 non-null  float64
 25  minimum_nights                               13466 non-null  float64
 26  maximum_nights                               13466 non-null  float64
 27  has_availability                             13452 non-null  str
 28  availability_30                              13472 non-null  int64
 29  availability_60                              13472 non-null  int64
 30  availability_90                              13472 non-null  int64
 31  availability_365                             13472 non-null  int64
 32  number_of_reviews                            13472 non-null  int64
 33  number_of_reviews_ltm                        13472 non-null  int64
 34  number_of_reviews_l30d                       13472 non-null  int64
 35  estimated_occupancy_l365d                    13472 non-null  int64
 36  estimated_revenue_l365d                      12448 non-null  float64
 37  first_review                                 12205 non-null  str
 38  last_review                                  12205 non-null  str
 39  review_scores_rating                         12205 non-null  float64
 40  review_scores_accuracy                       12205 non-null  float64
 41  review_scores_cleanliness                    12205 non-null  float64
 42  review_scores_checkin                        12205 non-null  float64
 43  review_scores_communication                  12205 non-null  float64
 44  review_scores_location                       12205 non-null  float64
 45  review_scores_value                          12205 non-null  float64
 46  license                                      12324 non-null  str
 47  calculated_host_listings_count               13472 non-null  int64
 48  calculated_host_listings_count_entire_homes  13472 non-null  int64
 49  reviews_per_month                            12205 non-null  float64
dtypes: float64(18), int64(16), str(16)
memory usage: 5.1 MB

In [46]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
# Crear copia para aplicar sustitución de valores nulos
data2 = data.copy()

# Sustituir valores nulos de una columna categórica con la moda
moda_host_location = data2["host_location"].mode().iloc[0]
data2["host_location"] = data2["host_location"].fillna(moda_host_location)

In [47]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                      1778
bedrooms                                       1634
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                        1024
price_quote_price_per_night                    1024
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [48]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["bathrooms"] = data2["bathrooms"].fillna(round(data2["bathrooms"].median(), 1))

In [49]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["price_quote_total_price"] = data2["price_quote_total_price"].fillna(round(data2["price_quote_total_price"].median(), 1))

In [50]:

#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["price_quote_price_per_night"] = data2["price_quote_price_per_night"].fillna(round(data2["price_quote_price_per_night"].median(), 1))

In [51]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                       1634
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [52]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                       1634
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [53]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
data2["bedrooms"]= data2["bedrooms"].fillna(0) 
data2

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13467,1715912359275006217,Central Station Elegant Boutique Room With Ens...,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13468,1715924716827942680,Central Station Grand Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13469,1715936169133608202,Central Station Modern Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13470,1715980987031944374,Ognissanti Blue House by Maison Florence,47559514,Maison Florence,10,2,"Florence, Italy",f,31,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2X4FYIGFF,31,31,NaN
13471,1715987897090686076,Stanza privata con bagno privato e AC in centro,66886740,Rosanna,10,7,"Florence, Italy",f,30,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,0,NaN

In [54]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                           1368
amenities                                         0
price_quote_checkin_date                        788
price_quote_checkout_date                       788
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [55]:
data2["beds"] = data2["beds"].fillna( data2["beds"].median())
data2

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13467,1715912359275006217,Central Station Elegant Boutique Room With Ens...,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13468,1715924716827942680,Central Station Grand Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13469,1715936169133608202,Central Station Modern Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,NaN
13470,1715980987031944374,Ognissanti Blue House by Maison Florence,47559514,Maison Florence,10,2,"Florence, Italy",f,31,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2X4FYIGFF,31,31,NaN
13471,1715987897090686076,Stanza privata con bagno privato e AC in centro,66886740,Rosanna,10,7,"Florence, Italy",f,30,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,0,NaN

In [63]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [57]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["price_quote_checkin_date"] =data2["price_quote_checkin_date"].fillna("Sin fecha")

In [67]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["license"] =data2["license"].fillna("Sin licencia")

In [68]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                           0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [59]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["price_quote_checkout_date"] =data2["price_quote_checkout_date"].fillna("Sin fecha")

In [60]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                        1148
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                              1267
dtype: int64

In [69]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["reviews_per_month"] =data2["reviews_per_month"].fillna("0")

In [70]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                           0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                                 0
dtype: int64

In [72]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                           0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                                 0
dtype: int64

In [73]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(12459)

**Método de Eliminación de valores nulos**

In [74]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                0
name                                              0
host_id                                           0
host_name                                         0
hosts_time_as_user_years                          0
hosts_time_as_host_years                          0
host_location                                     0
host_is_superhost                                 0
host_listings_count                               0
host_has_profile_pic                              0
host_identity_verified                            0
neighbourhood_cleansed                            0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
amenities                                         0
price_quote_checkin_date                          0
price_quote_checkout_date                         0
price_quote_total_price                           0
price_quote_price_per_night                       0
minimum_nights                                    6
maximum_nights                                    6
has_availability                                 20
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
estimated_occupancy_l365d                         0
estimated_revenue_l365d                        1024
first_review                                   1267
last_review                                    1267
review_scores_rating                           1267
review_scores_accuracy                         1267
review_scores_cleanliness                      1267
review_scores_checkin                          1267
review_scores_communication                    1267
review_scores_location                         1267
review_scores_value                            1267
license                                           0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
reviews_per_month                                 0
dtype: int64

In [75]:
#Realizamos una copia del dataframe
data3=data2.copy()
data3

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13467,1715912359275006217,Central Station Elegant Boutique Room With Ens...,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,0
13468,1715924716827942680,Central Station Grand Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,0
13469,1715936169133608202,Central Station Modern Boutique Room With Ensuite,673533626,Lorenzo,1,1,"Florence, Italy",t,23,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2DIKOFZN9,14,5,0
13470,1715980987031944374,Ognissanti Blue House by Maison Florence,47559514,Maison Florence,10,2,"Florence, Italy",f,31,t,...,NaN,NaN,NaN,NaN,NaN,NaN,IT048017C2X4FYIGFF,31,31,0
13471,1715987897090686076,Stanza privata con bagno privato e AC in centro,66886740,Rosanna,10,7,"Florence, Italy",f,30,t,...,NaN,NaN,NaN,NaN,NaN,NaN,Sin licencia,24,0,0

In [80]:
#Identificar valores nulos por columna
valores_nulos=data3.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [81]:
data3.info()

<class 'pandas.DataFrame'>
Index: 11344 entries, 0 to 13449
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           11344 non-null  int64
 1   name                                         11344 non-null  str
 2   host_id                                      11344 non-null  int64
 3   host_name                                    11344 non-null  str
 4   hosts_time_as_user_years                     11344 non-null  int64
 5   hosts_time_as_host_years                     11344 non-null  int64
 6   host_location                                11344 non-null  str
 7   host_is_superhost                            11344 non-null  str
 8   host_listings_count                          11344 non-null  int64
 9   host_has_profile_pic                         11344 non-null  str
 10  host_identity_verified                       11344 non-null  str
 11  neighbourhood_cleansed                       11344 non-null  str
 12  latitude                                     11344 non-null  float64
 13  longitude                                    11344 non-null  float64
 14  property_type                                11344 non-null  str
 15  room_type                                    11344 non-null  str
 16  accommodates                                 11344 non-null  int64
 17  bathrooms                                    11344 non-null  float64
 18  bedrooms                                     11344 non-null  float64
 19  beds                                         11344 non-null  float64
 20  amenities                                    11344 non-null  str
 21  price_quote_checkin_date                     11344 non-null  str
 22  price_quote_checkout_date                    11344 non-null  str
 23  price_quote_total_price                      11344 non-null  float64
 24  price_quote_price_per_night                  11344 non-null  float64
 25  minimum_nights                               11344 non-null  float64
 26  maximum_nights                               11344 non-null  float64
 27  has_availability                             11344 non-null  str
 28  availability_30                              11344 non-null  int64
 29  availability_60                              11344 non-null  int64
 30  availability_90                              11344 non-null  int64
 31  availability_365                             11344 non-null  int64
 32  number_of_reviews                            11344 non-null  int64
 33  number_of_reviews_ltm                        11344 non-null  int64
 34  number_of_reviews_l30d                       11344 non-null  int64
 35  estimated_occupancy_l365d                    11344 non-null  int64
 36  estimated_revenue_l365d                      11344 non-null  float64
 37  first_review                                 11344 non-null  str
 38  last_review                                  11344 non-null  str
 39  review_scores_rating                         11344 non-null  float64
 40  review_scores_accuracy                       11344 non-null  float64
 41  review_scores_cleanliness                    11344 non-null  float64
 42  review_scores_checkin                        11344 non-null  float64
 43  review_scores_communication                  11344 non-null  float64
 44  review_scores_location                       11344 non-null  float64
 45  review_scores_value                          11344 non-null  float64
 46  license                                      11344 non-null  str
 47  calculated_host_listings_count               11344 non-null  int64
 48  calculated_host_listings_count_entire_homes  11344 non-null  int64
 49  reviews_per_month                            11344 non-null  object
dtypes: float64(17), int64(16), object(1), str(16)
memory usage: 4.4+ MB

**Convertir DataSet sin valores nulos a CSV**

In [83]:
#Convertir DataFrame a CSV
data3.to_csv("listings_Florencia_sin_nulos.csv")

In [85]:


# DESCRIPCION DEL TRATAMIENTO DE VALORES NULOS POR VARIABLE

# salon_ventas:
# Los valores nulos se sustituyeron utilizando la media, redondeada a un decimal.

# subtotal_ventas_alimentos_bebidas:
# Los valores nulos se sustituyeron utilizando la mediana, redondeada a un decimal.

# tarjetas_credito:
# Los valores nulos se sustituyeron por el valor numerico concreto 5.

# indice_tiempo:
# Los valores nulos se sustituyeron por la fecha concreta "2030-06-19 00:00:00".

# otros_medios:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# tarjetas_debito:
# Se utilizo backward fill (bfill), tomando el siguiente valor valido.

# otros:
# Se utilizo backward fill (bfill), tomando el siguiente valor valido.

# indumentaria_calzado_textiles_hogar:
# Se utilizo backward fill (bfill), tomando el siguiente valor valido.

# electronicos_articulos_hogar:
# Se utilizo backward fill (bfill), tomando el siguiente valor valido.

# panaderia:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# lacteos:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# bebidas:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# carnes:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# almacen:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# verduleria_fruteria:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# alimentos_preparados_rotiseria:
# Se utilizo forward fill (ffill), tomando el ultimo valor valido anterior.

# Las demas variables no presentaron valores nulos,
# por lo que no fue necesario aplicar alguna tecnica de sustitucion.

In [ ]:
#descargar archivo filtrado en csv desde COLAB
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")