<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [91]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [92]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('listings_Florencia.csv')
data.head(5)

,Unnamed: 0,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20

In [93]:
columnas = [
    "id",
    "name",
    "host_id",
    "host_name",
    "hosts_time_as_user_years",
    "hosts_time_as_host_years",
    "host_location",
    "host_is_superhost",
    "host_listings_count",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "amenities",
    "price_quote_checkin_date",
    "price_quote_checkout_date",
    "price_quote_total_price",
    "price_quote_price_per_night",
    "minimum_nights",
    "maximum_nights",
    "has_availability",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "first_review",
    "last_review",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "license",
    "calculated_host_listings_count",
    "calculated_host_listings_count_entire_homes",
    "reviews_per_month"
]
data = data[columnas]
data

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,1705217620865583039,Healthy Home | David Secret Gallery,38905787,Healthy Home Di Clarissa & Andrea,10,10,"Florence, Italy",t,12,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2XOJLYGJP,8,8,3.00
11340,1706426569976555746,Villino degli Ulivi vicino al centro Careggi M...,419464187,Silvia,4,3,"Florence, Italy",f,2,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2I8TS2NJL,2,2,1.00
11341,1706511819293760229,Over the Rooftops of Florence – Historic Center,1706505190372298282,Sandra,0,0,"Florence, Italy",f,1,f,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C23NQD3X41,1,1,1.00
11342,1709442565530728413,"Viola Apartment | House with Terrace, Firenze",100826568,Rosso Fiorentino,9,0,"Rome, Italy",f,1,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2NWAKZRNS,1,1,1.00
11343,1712238188314726142,Airport Comfort Room,550360172,Nataliia,2,2,"Florence, Italy",f,3,t,...,5.00,5.00,5.00,5.00,3.50,5.00,IT048017C2TKVP2AAG,3,1,2.00

In [94]:
# Seleccionar únicamente las 50 columnas
data = data[columnas]

# Crear una copia con esas 50 columnas
data2 = data.copy()

# Identificar valores nulos solamente en las 50 columnas
valores_nulos = data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [95]:
data2 = data.copy()

In [96]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [97]:
#Identificar valores nulos por dataframe
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(0)

In [98]:
# JUSTIFICACION DEL TRATAMIENTO DE VALORES NULOS

# host_location:
# Se utilizo la moda porque es una variable categorica y permite sustituir
# los nulos con la ubicacion que aparece con mayor frecuencia.

# bathrooms:
# Se utilizo la mediana porque es una variable numerica y este metodo
# evita que los alojamientos con muchos baños alteren la sustitucion.

# price_quote_total_price:
# Se utilizo la mediana porque existen precios extremos que pueden afectar el promedio.

# price_quote_price_per_night:
# Se utilizo la mediana porque los precios por noche presentan valores extremos.

# bedrooms:
# Se utilizo el valor numerico 0 para representar posibles alojamientos tipo estudio.

# beds:
# Se utilizo la mediana porque es una variable numerica y puede presentar
# alojamientos con cantidades de camas muy altas.

# price_quote_checkin_date:
# Se utilizo el string "Sin fecha" para identificar los registros
# que no contaban con una fecha de entrada.

# price_quote_checkout_date:
# Se utilizo el string "Sin fecha" para identificar los registros
# que no contaban con una fecha de salida.

# license:
# Se utilizo el string "Sin licencia" para conservar los alojamientos
# que no tenian una licencia registrada.

# reviews_per_month:
# Se utilizo el valor numerico 0 para representar alojamientos
# que no registraron reseñas durante el mes.

# En las variables restantes que presentaban valores nulos se eliminaron
# las filas incompletas mediante dropna(), porque no se aplico otro metodo
# de sustitucion y se necesitaba generar un archivo final sin valores nulos.

# Las demas variables no necesitaron tratamiento porque originalmente
# no presentaban valores nulos.

**Métodos de Sustitución de Valores Nulos**

In [99]:
#Realizamos una copia del dataframe
data2=data.copy()

In [100]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 11344 entries, 0 to 11343
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           11344 non-null  int64
 1   name                                         11344 non-null  str
 2   host_id                                      11344 non-null  int64
 3   host_name                                    11344 non-null  str
 4   hosts_time_as_user_years                     11344 non-null  int64
 5   hosts_time_as_host_years                     11344 non-null  int64
 6   host_location                                11344 non-null  str
 7   host_is_superhost                            11344 non-null  str
 8   host_listings_count                          11344 non-null  int64
 9   host_has_profile_pic                         11344 non-null  str
 10  host_identity_verified                       11344 non-null  str
 11  neighbourhood_cleansed                       11344 non-null  str
 12  latitude                                     11344 non-null  float64
 13  longitude                                    11344 non-null  float64
 14  property_type                                11344 non-null  str
 15  room_type                                    11344 non-null  str
 16  accommodates                                 11344 non-null  int64
 17  bathrooms                                    11344 non-null  float64
 18  bedrooms                                     11344 non-null  float64
 19  beds                                         11344 non-null  float64
 20  amenities                                    11344 non-null  str
 21  price_quote_checkin_date                     11344 non-null  str
 22  price_quote_checkout_date                    11344 non-null  str
 23  price_quote_total_price                      11344 non-null  float64
 24  price_quote_price_per_night                  11344 non-null  float64
 25  minimum_nights                               11344 non-null  float64
 26  maximum_nights                               11344 non-null  float64
 27  has_availability                             11344 non-null  str
 28  availability_30                              11344 non-null  int64
 29  availability_60                              11344 non-null  int64
 30  availability_90                              11344 non-null  int64
 31  availability_365                             11344 non-null  int64
 32  number_of_reviews                            11344 non-null  int64
 33  number_of_reviews_ltm                        11344 non-null  int64
 34  number_of_reviews_l30d                       11344 non-null  int64
 35  estimated_occupancy_l365d                    11344 non-null  int64
 36  estimated_revenue_l365d                      11344 non-null  float64
 37  first_review                                 11344 non-null  str
 38  last_review                                  11344 non-null  str
 39  review_scores_rating                         11344 non-null  float64
 40  review_scores_accuracy                       11344 non-null  float64
 41  review_scores_cleanliness                    11344 non-null  float64
 42  review_scores_checkin                        11344 non-null  float64
 43  review_scores_communication                  11344 non-null  float64
 44  review_scores_location                       11344 non-null  float64
 45  review_scores_value                          11344 non-null  float64
 46  license                                      11344 non-null  str
 47  calculated_host_listings_count               11344 non-null  int64
 48  calculated_host_listings_count_entire_homes  11344 non-null  int64
 49  reviews_per_month                            11344 non-null  float64
dtypes: float64(18), int64(16), str(16)
memory usage: 4.3 MB

In [101]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
# Crear copia para aplicar sustitución de valores nulos
data2 = data.copy()

# Sustituir valores nulos de una columna categórica con la moda
moda_host_location = data2["host_location"].mode().iloc[0]
data2["host_location"] = data2["host_location"].fillna(moda_host_location)

In [102]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [103]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["bathrooms"] = data2["bathrooms"].fillna(round(data2["bathrooms"].median(), 1))

In [104]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["price_quote_total_price"] = data2["price_quote_total_price"].fillna(round(data2["price_quote_total_price"].median(), 1))

In [105]:

#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data2["price_quote_price_per_night"] = data2["price_quote_price_per_night"].fillna(round(data2["price_quote_price_per_night"].median(), 1))

In [106]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [107]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [108]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
data2["bedrooms"]= data2["bedrooms"].fillna(0) 
data2

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,1705217620865583039,Healthy Home | David Secret Gallery,38905787,Healthy Home Di Clarissa & Andrea,10,10,"Florence, Italy",t,12,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2XOJLYGJP,8,8,3.00
11340,1706426569976555746,Villino degli Ulivi vicino al centro Careggi M...,419464187,Silvia,4,3,"Florence, Italy",f,2,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2I8TS2NJL,2,2,1.00
11341,1706511819293760229,Over the Rooftops of Florence – Historic Center,1706505190372298282,Sandra,0,0,"Florence, Italy",f,1,f,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C23NQD3X41,1,1,1.00
11342,1709442565530728413,"Viola Apartment | House with Terrace, Firenze",100826568,Rosso Fiorentino,9,0,"Rome, Italy",f,1,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2NWAKZRNS,1,1,1.00
11343,1712238188314726142,Airport Comfort Room,550360172,Nataliia,2,2,"Florence, Italy",f,3,t,...,5.00,5.00,5.00,5.00,3.50,5.00,IT048017C2TKVP2AAG,3,1,2.00

In [109]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [110]:
data2["beds"] = data2["beds"].fillna( data2["beds"].median())
data2

,id,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_host_years,host_location,host_is_superhost,host_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,31840,Residenza Martin Classic room,380378,Andrea Frua De Angeli,15,15,"Florence, Italy",t,31,t,...,4.77,4.86,4.87,4.91,4.90,4.71,IT048017B4R5K5BW8E,22,13,1.05
1,32180,Charming Gem - Oltrarno City centre,13925330,Cesare,12,12,"Florence, Italy",t,1,t,...,4.84,4.84,4.81,4.72,4.84,4.84,IT048017C232S8WUEN,1,1,0.24
2,39115,Central Double Shared Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.71,4.62,4.82,4.75,4.92,4.57,IT048017B9LED47MUB,11,3,0.48
3,39165,Florence Central Double Private Bathroom,167739,Lorenzo,15,15,"Florence, Italy",f,11,t,...,4.35,4.57,4.74,4.65,4.96,4.43,IT048017B9LED47MUB,11,3,0.13
4,39822,Apartment Santa Monaca Oltrarno old town,154769,Matilde,15,15,"Florence, Italy",f,3,t,...,4.46,4.51,4.71,4.74,4.89,4.54,IT048017C2VVSRW6CW,3,3,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,1705217620865583039,Healthy Home | David Secret Gallery,38905787,Healthy Home Di Clarissa & Andrea,10,10,"Florence, Italy",t,12,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2XOJLYGJP,8,8,3.00
11340,1706426569976555746,Villino degli Ulivi vicino al centro Careggi M...,419464187,Silvia,4,3,"Florence, Italy",f,2,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2I8TS2NJL,2,2,1.00
11341,1706511819293760229,Over the Rooftops of Florence – Historic Center,1706505190372298282,Sandra,0,0,"Florence, Italy",f,1,f,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C23NQD3X41,1,1,1.00
11342,1709442565530728413,"Viola Apartment | House with Terrace, Firenze",100826568,Rosso Fiorentino,9,0,"Rome, Italy",f,1,t,...,5.00,5.00,5.00,5.00,5.00,5.00,IT048017C2NWAKZRNS,1,1,1.00
11343,1712238188314726142,Airport Comfort Room,550360172,Nataliia,2,2,"Florence, Italy",f,3,t,...,5.00,5.00,5.00,5.00,3.50,5.00,IT048017C2TKVP2AAG,3,1,2.00

In [111]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [112]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["price_quote_checkin_date"] =data2["price_quote_checkin_date"].fillna("Sin fecha")

In [113]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["license"] =data2["license"].fillna("Sin licencia")

In [114]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [115]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["price_quote_checkout_date"] =data2["price_quote_checkout_date"].fillna("Sin fecha")

In [116]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [117]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data2["reviews_per_month"] =data2["reviews_per_month"].fillna(0)

In [118]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [119]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [120]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(0)

**Método de Eliminación de valores nulos**

In [121]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

In [122]:
# Realizamos una copia del dataframe después de las sustituciones
data3 = data2.copy()

# En las variables restantes se eliminaron las filas con valores nulos,
# debido a que no se aplicó otro método de sustitución.
data3 = data3.dropna()

# Comprobar que ya no existan valores nulos
valores_nulos = data3.isnull().sum().sum()
valores_nulos

np.int64(0)

In [123]:
#Identificar valores nulos por columna
valores_nulos=data3.isnull().sum()
valores_nulos

id                                             0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_host_years                       0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_has_profile_pic                           0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
amenities                                      0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_l30d                         0
estimated_occupancy_l365d                      0
estimated_revenue_l365d                        0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_cleanliness                      0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
license                                        0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
reviews_per_month                              0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [124]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 11344 entries, 0 to 11343
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           11344 non-null  int64
 1   name                                         11344 non-null  str
 2   host_id                                      11344 non-null  int64
 3   host_name                                    11344 non-null  str
 4   hosts_time_as_user_years                     11344 non-null  int64
 5   hosts_time_as_host_years                     11344 non-null  int64
 6   host_location                                11344 non-null  str
 7   host_is_superhost                            11344 non-null  str
 8   host_listings_count                          11344 non-null  int64
 9   host_has_profile_pic                         11344 non-null  str
 10  host_identity_verified                       11344 non-null  str
 11  neighbourhood_cleansed                       11344 non-null  str
 12  latitude                                     11344 non-null  float64
 13  longitude                                    11344 non-null  float64
 14  property_type                                11344 non-null  str
 15  room_type                                    11344 non-null  str
 16  accommodates                                 11344 non-null  int64
 17  bathrooms                                    11344 non-null  float64
 18  bedrooms                                     11344 non-null  float64
 19  beds                                         11344 non-null  float64
 20  amenities                                    11344 non-null  str
 21  price_quote_checkin_date                     11344 non-null  str
 22  price_quote_checkout_date                    11344 non-null  str
 23  price_quote_total_price                      11344 non-null  float64
 24  price_quote_price_per_night                  11344 non-null  float64
 25  minimum_nights                               11344 non-null  float64
 26  maximum_nights                               11344 non-null  float64
 27  has_availability                             11344 non-null  str
 28  availability_30                              11344 non-null  int64
 29  availability_60                              11344 non-null  int64
 30  availability_90                              11344 non-null  int64
 31  availability_365                             11344 non-null  int64
 32  number_of_reviews                            11344 non-null  int64
 33  number_of_reviews_ltm                        11344 non-null  int64
 34  number_of_reviews_l30d                       11344 non-null  int64
 35  estimated_occupancy_l365d                    11344 non-null  int64
 36  estimated_revenue_l365d                      11344 non-null  float64
 37  first_review                                 11344 non-null  str
 38  last_review                                  11344 non-null  str
 39  review_scores_rating                         11344 non-null  float64
 40  review_scores_accuracy                       11344 non-null  float64
 41  review_scores_cleanliness                    11344 non-null  float64
 42  review_scores_checkin                        11344 non-null  float64
 43  review_scores_communication                  11344 non-null  float64
 44  review_scores_location                       11344 non-null  float64
 45  review_scores_value                          11344 non-null  float64
 46  license                                      11344 non-null  str
 47  calculated_host_listings_count               11344 non-null  int64
 48  calculated_host_listings_count_entire_homes  11344 non-null  int64
 49  reviews_per_month                            11344 non-null  float64
dtypes: float64(18), int64(16), str(16)
memory usage: 4.3 MB

**Convertir DataSet sin valores nulos a CSV**

In [128]:
#Convertir DataFrame a CSV
data3.to_csv("listings_Florencia_sin_nulos.csv")